###

POST http://localhost:3000/comments 
Content-Type: application/json

{
    "sender": "Linoy",
    "comment": "My new comment", 
    "postId": "67447cf4db214c2ad9a696d2"
}

###

GET http://localhost:3000/comments/67448d4b1829e8c078e3d9e4


###

PUT http://localhost:3000/comments/67448c6f1829e8c078e3d9d7
Content-Type: application/json

{
    "comment": "My updated comment"
}


###

DELETE http://localhost:3000/comments/67448c6f1829e8c078e3d9d7